//
//  Language.swift
//  LeBaluchon
//
//  Created by Sergio Canto  on 18/12/2020.
//

import Foundation

//MARK: - Public propertie

// This constant contain all the available languagesFor the translation
// code: code for the API
// descr: description to show on the app

let language: [(code: String, languageName: String)] =

    [("af", "Afrikaans"),
    ("sq", "Albanian"),
    ("de", "German"),
    ("am", "Amharic"),
    ("en", "English"),
    ("ar", "Arab"),
    ("hy", "Armenian"),
    ("az", "Azeri"),
    ("eu", "Basque"),
    ("bn", "Bengali"),
    ("be", "Belarusian"),
    ("my", "Burmese"),
    ("bs", "Bosnian"),
    ("bg", "Bulgarian"),
    ("ca", "Catalan"),
    ("ceb", "Cebuano"),
    ("ny", "Chichewa"),
    ("zh", "Chinese (simplified)"),
    ("zh-TW", "Chinese (traditional)"),
    ("si", "Sinhala"),
    ("ko", "Korean"),
    ("co", "Corsica"),
    ("ht", "Haitian creole"),
    ("hr", "Croatian"),
    ("da", "Danish"),
    ("es", "Spanish"),
    ("eo", "Esperanto"),
    ("et", "Estonian"),
    ("fi", "Finnish"),
    ("fr", "French"),
    ("fy", "Frisian"),
    ("gd", "Gaelic (Scotland)"),
    ("gl", "Galician"),
    ("cy", "Welsh"),
    ("ka", "Georgian"),
    ("el", "Greek"),
    ("gu", "Gujarati"),
    ("ha", "Hausa"),
    ("haw", "Hawaiian"),
    ("iw", "Hebrew"),
    ("hi", "Hindi"),
    ("hmn", "Hmong"),
    ("hu", "Hungarian"),
    ("ig", "Igbo"),
    ("id", "Indonesian"),
    ("ga", "Irish"),
    ("is", "Icelandic"),
    ("it", "Italian"),
    ("ja", "Japanese"),
    ("jw", "Javanese"),
    ("kn", "Kannada"),
    ("kk", "Kazakh"),
    ("km", "Khmer"),
    ("ky", "Kirghiz"),
    ("ku", "Kurdish"),
    ("lo", "Laotian"),
    ("la", "Latin"),
    ("lv", "Latvian"),
    ("lt", "Lithuanian"),
    ("lb", "Luxembourgish"),
    ("mk", "Macedonian"),
    ("ms", "Malaysian"),
    ("ml", "Malayalam"),
    ("mg", "Malagasy"),
    ("mt", "Maltese"),
    ("mi", "Maori"),
    ("mr", "Marathi"),
    ("mn", "Mongolian"),
    ("nl", "Dutch"),
    ("ne", "Nepali"),
    ("no", "Norwegian"),
    ("uz", "Uzbek"),
    ("ps", "Pashto"),
    ("pa", "Panjabi"),
    ("fa", "Persian"),
    ("pl", "Polish"),
    ("pt", "Portuguese"),
    ("ro", "Romanian"),
    ("ru", "Russian"),
    ("sm", "Samoan"),
    ("sr", "Serbian"),
    ("st", "Sesotho"),
    ("sn", "Shona"),
    ("sd", "Sindhî"),
    ("sk", "Slovak"),
    ("sl", "Slovenian"),
    ("so", "Somali"),
    ("su", "Soundanese"),
    ("sv", "Swedish"),
    ("sw", "Swahili"),
    ("tg", "Tajik"),
    ("tl", "Tagalog"),
    ("ta", "Tamil"),
    ("cs", "Czech"),
    ("te", "Telugu"),
    ("th", "Thai"),
    ("tr", "Turkish"),
    ("uk", "Ukrainian"),
    ("ur", "Urdu"),
    ("vi", "Vietnamese"),
    ("xh", "Xhosa"),
    ("yi", "Yiddish"),
    ("yo", "Yorouba"),
    ("zu", "Zulu")]
