//
//  Language.swift
//  LeBaluchon
//
//  Created by Sergio Canto  on 12/11/2020.
//

import Foundation

// This constant contain all the available languages
// For the translation
// code: code for the API
// descr: description to show on the app

let language: [(code: String, descr: String)] =

    [("af", "Afrikaans"),
    ("sq", "Albanais"),
    ("de", "Allemand"),
    ("am", "Amharique"),
    ("en", "Anglais"),
    ("ar", "Arabe"),
    ("hy", "Arménien"),
    ("az", "Azéri"),
    ("eu", "Basque"),
    ("bn", "Bengali"),
    ("be", "Biélorusse"),
    ("my", "Birman"),
    ("bs", "Bosniaque"),
    ("bg", "Bulgare"),
    ("ca", "Catalan"),
    ("ceb", "Cebuano"),
    ("ny", "Chichewa"),
    ("zh", "Chinois (simplifié)"),
    ("zh-TW", "Chinois (traditionnel)"),
    ("si", "Cingalais"),
    ("ko", "Coréen"),
    ("co", "Corse"),
    ("ht", "Créole haïtien"),
    ("hr", "Croate"),
    ("da", "Danois"),
    ("es", "Espagnol"),
    ("eo", "Espéranto"),
    ("et", "Estonien"),
    ("fi", "Finnois"),
    ("fr", "Français"),
    ("fy", "Frison"),
    ("gd", "Gaélique (Écosse)"),
    ("gl", "Galicien"),
    ("cy", "Gallois"),
    ("ka", "Géorgien"),
    ("el", "Grec"),
    ("gu", "Gujarati"),
    ("ha", "Haoussa"),
    ("haw", "Hawaïen"),
    ("iw", "Hébreu"),
    ("hi", "Hindi"),
    ("hmn", "Hmong"),
    ("hu", "Hongrois"),
    ("ig", "Igbo"),
    ("id", "Indonésien"),
    ("ga", "Irlandais"),
    ("is", "Islandais"),
    ("it", "Italien"),
    ("ja", "Japonais"),
    ("jw", "Javanais"),
    ("kn", "Kannada"),
    ("kk", "Kazakh"),
    ("km", "Khmer"),
    ("ky", "Kirghiz"),
    ("ku", "Kurde"),
    ("lo", "Laotien"),
    ("la", "Latin"),
    ("lv", "Letton"),
    ("lt", "Lituanien"),
    ("lb", "Luxembourgeois"),
    ("mk", "Macédonien"),
    ("ms", "Malaisien"),
    ("ml", "Malayalam"),
    ("mg", "Malgache"),
    ("mt", "Maltais"),
    ("mi", "Maori"),
    ("mr", "Marathi"),
    ("mn", "Mongol"),
    ("nl", "Néerlandais"),
    ("ne", "Népalais"),
    ("no", "Norvégien"),
    ("uz", "Ouzbek"),
    ("ps", "Pachtô"),
    ("pa", "Panjabi"),
    ("fa", "Persan"),
    ("pl", "Polonais"),
    ("pt", "Portugais"),
    ("ro", "Roumain"),
    ("ru", "Russe"),
    ("sm", "Samoan"),
    ("sr", "Serbe"),
    ("st", "Sesotho"),
    ("sn", "Shona"),
    ("sd", "Sindhî"),
    ("sk", "Slovaque"),
    ("sl", "Slovène"),
    ("so", "Somali"),
    ("su", "Soundanais"),
    ("sv", "Suédois"),
    ("sw", "Swahili"),
    ("tg", "Tadjik"),
    ("tl", "Tagalog"),
    ("ta", "Tamoul"),
    ("cs", "Tchèque"),
    ("te", "Telugu"),
    ("th", "Thaï"),
    ("tr", "Turc"),
    ("uk", "Ukrainien"),
    ("ur", "Urdu"),
    ("vi", "Vietnamien"),
    ("xh", "Xhosa"),
    ("yi", "Yiddish"),
    ("yo", "Yorouba"),
    ("zu", "Zoulou")]
