//
//  Countrys.swift
//  LeBaluchon
//
//  Created by Sergio Canto  on 06/11/2020.
//

import Foundation

var countrys = [africa, america, asia, europe, oceania]

let continent = ["Africa", "America", "Asia", "Europe", "Oceania"]

let africa = [
    "Afrique du Sud",
    "Algérie",
    "Angola",
    "Bénin",
    "Botswana",
    "Burkina Faso",
    "Burundi",
    "Cameroun",
    "Cap-Vert",
    "République centrafricaine",
    "Comores",
    "République du Congo",
    "République démocratique du Congo",
    "Côte d’Ivoire",
    "Djibouti",
    "Égypte",
    "Érythrée",
    "Eswatini",
    "Éthiopie",
    "Gabon",
    "Gambie",
    "Ghana",
    "Guinée",
    "Guinée-Bissau",
    "Guinée équatoriale",
    "Kenya",
    "Lesotho",
    "Liberia",
    "Libye",
    "Madagascar",
    "Malawi",
    "Mali",
    "Maroc",
    "Maurice",
    "Mauritanie",
    "Mozambique",
    "Namibie",
    "Niger",
    "Nigeria",
    "Ouganda",
    "Rwanda",
    "São Tomé-et-Principe",
    "Sénégal",
    "Seychelles",
    "Sierra Leone",
    "Somalie",
    "Soudan",
    "Soudan du Sud",
    "Tanzanie",
    "Tchad",
    "Togo",
    "Tunisie",
    "Zambie",
    "Zimbabwe"]

let america = [
    "Antigua-et-Barbuda",
    "Argentine",
    "Bahamas",
    "Barbade",
    "Belize",
    "Bolivie",
    " Brésil",
    "Canada",
    "Chili",
    "Colombie",
    "Costa Rica",
    "Cuba",
    "République Dominicaine",
    "Dominique",
    "Équateur",
    "États-Unis",
    "Grenade",
    " Guatemala",
    "Guyana",
    "Haïti",
    "Honduras",
    "Jamaïque",
    "Mexique",
    "Nicaragua",
    "Panama",
    "Paraguay",
    "Pérou",
    "Saint-Kitts-et-Nevis",
    "Saint-Vincent-et-les-Grenadines",
    "Sainte-Lucie",
    "Salvador",
    "Suriname",
    "Trinité-et-Tobago",
    "Uruguay",
    "Venezuela"]

let asia = [
    "Afghanistan",
    "Arabie Saoudite",
    "Arménie",
    "Azerbaïdjan",
    "Bahreïn",
    "Bangladesh",
    "Bhoutan",
    "Birmanie",
    "Brunei",
    "Cambodge",
    "Chine",
    "Corée du Nord",
    "Corée du Sud",
    "Émirats arabes unis",
    "Géorgie",
    "Inde",
    "Indonésie",
    "Irak",
    "Iran",
    "Israël",
    "Japon",
    "Jordanie",
    "Kazakhstan",
    "Kirghizistan",
    "Koweït",
    "Laos",
    "Liban",
    "Malaisie",
    "Maldives",
    "Mongolie",
    "Népal",
    "Oman",
    "Ouzbékistan",
    "Palestine",
    "Pakistan",
    "Philippines",
    "Qatar",
    "Singapour",
    "Sri Lanka",
    "Syrie",
    "Tadjikistan",
    "Thaïlande",
    "Timor oriental",
    "Turkménistan",
    "Turquie",
    "Viêt Nam",
    "Yémen"]

let europe = [
    "Albanie",
    "Allemagne",
    "Andorre",
    "Autriche",
    "Belgique",
    "Biélorussie",
    "Bosnie-Herzégovine",
    "Bulgarie",
    "Chypre",
    "Croatie",
    "Danemark",
    "Espagne",
    "Estonie",
    "Finlande",
    "France",
    "Grèce",
    "Hongrie",
    "Irlande",
    "Islande",
    "Italie",
    "Kosovo",
    "Lettonie",
    "Liechtenstein",
    "Lituanie",
    "Luxembourg",
    "Macédoine",
    "Malte",
    "Moldavie",
    "Monaco",
    "Monténégro",
    "Norvège",
    "Pays-Bas",
    "Pologne",
    "Portugal",
    "République tchèque",
    "Roumanie",
    "Royaume-Uni",
    "Russie",
    "Saint-Marin",
    "Serbie",
    "Slovaquie",
    "Slovénie",
    "Suède",
    "Suisse",
    "Ukraine",
    "Vatican"]

let oceania = [
    "Australie",
    "Îles Cook",
    "Fidji",
    "Kiribati",
    "Îles Marshall",
    "Micronésie",
    "Nauru",
    "Niue",
    "Nouvelle-Zélande",
    "Palaos",
    "Papouasie-Nouvelle-Guinée",
    "Salomon",
    "Samoa",
    "Tonga",
    "Tuvalu",
    "Vanuatu"]

